BISTTool/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BISTTool.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BISTTool/Pages/Index.cshtml.cs
using BIST.Utilities;
using BIST.Utilities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BISTTool.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly FinancialCalculatorAssistant service;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            service = new FinancialCalculatorAssistant();
            this.Start();
            this.ThreadStarter();
            this.ReportThreadStarter();
        }


        public void ThreadStarter()
        {
            var borsaKZThread = new System.Threading.Thread(new System.Threading.ThreadStart(async () =>
            {
                BISTReports = System.IO.File.Exists(reportPath) ? JsonConvert.DeserializeObject<List<BISTReport>>(System.IO.File.ReadAllText(reportPath)) : new List<BISTReport>();
                a = service.CalculateBISTProfit();
                UsdPrice = service.GetUsdTryPrice();
                var list = a.Values.First();
                satilan = list.Where(br => br.isPartiallySelled || br.isTotallySelled).OrderByDescending(br => br.BirimDegisimYuzde).ToList();
                elde = list.Where(br => !(br.isPartiallySelled || br.isTotallySelled)).OrderByDescending(br => br.BirimDegisimYuzde).ToList();
                BISTResults = elde.Union(satilan).ToList();
                Task.Delay(100 * 60 * 30).Wait();
            }));
            borsaKZThread.Name = "CalculateKZ";
            borsaKZThread.Start();
        }

        private string reportPath = "report.json";

        public void ReportThreadStarter()
        {
            var reportThread = new System.Threading.Thread(new System.Threading.ThreadStart(async () =>
            {
                if (DateTime.Today.DayOfWeek != DayOfWeek.Sunday && DateTime.Today.DayOfWeek != DayOfWeek.Saturday)
                {
                    if (!System.IO.File.Exists(reportPath) && DateTime.Now.Hour > 18)
                    {
                        double totalTutar = a.Keys.First().Keys.First();
                        double currentTotal = a.Keys.First().Values.First();

                        var dailyReport = new BISTReport()
                        {
                            Date = DateTime.Today,
                            TotalMaliyet = totalTutar,
                            TotalKz = currentTotal - totalTutar,
                            USDTRY = this.UsdPrice,
                            PortfolioTotal = currentTotal,
                            TotalMaliyetUSD = service.TotalMaliyetUSD,
                            TotalKzUSD = currentTotal / UsdPrice - service.TotalMaliyetUSD,
                            PortfolioTotalUSD = currentTotal / UsdPrice
                        };

                        var reports = new List<BISTReport>() { dailyReport };

                        System.IO.File.WriteAllText(reportPath, JsonConvert.SerializeObject(reports));
                    }
                    else if (System.IO.File.Exists(reportPath) && DateTime.Now.Hour > 18)
                    {
                        var reports = JsonConvert.DeserializeObject<List<BISTReport>>(System.IO.File.ReadAllText(reportPath));
                        if (!reports.Any(r => r.Date == DateTime.Today))
                        {
                            double totalTutar = a.Keys.First().Keys.First();
                            double currentTotal = a.Keys.First().Values.First();
                            var dailyReport = new BISTReport()
                            {
                                Date = DateTime.Today,
                                TotalMaliyet = totalTutar,
                                TotalKz = currentTotal - totalTutar,
                                USDTRY = this.UsdPrice,
                                PortfolioTotal = currentTotal,
                                TotalMaliyetUSD = service.TotalMaliyetUSD,
                                TotalKzUSD = currentTotal / UsdPrice - service.TotalMaliyetUSD,
                                PortfolioTotalUSD = currentTotal / UsdPrice
                            };

                            reports.Add(dailyReport);

                            System.IO.File.WriteAllText(reportPath, JsonConvert.SerializeObject(reports));
                        }
                    }
                }

                Task.Delay(100 * 60 * 30).Wait();
            }));
            reportThread.Name = "reportThread";
            reportThread.Start();
        }


        public void Start()
        {
            BISTReports = System.IO.File.Exists(reportPath) ? JsonConvert.DeserializeObject<List<BISTReport>>(System.IO.File.ReadAllText(reportPath)) : new List<BISTReport>();
            a = service.CalculateBISTProfit();
            UsdPrice = service.GetUsdTryPrice();
            var list = a.Values.First();
            satilan = list.Where(br => br.isPartiallySelled || br.isTotallySelled).OrderByDescending(br => br.BirimDegisimYuzde).ToList();
            elde = list.Where(br => !(br.isPartiallySelled || br.isTotallySelled)).OrderByDescending(br => br.BirimDegisimYuzde).ToList();
            BISTResults = elde.Union(satilan).ToList();
        }

        public IActionResult OnPostMyButtonClick()
        {
            BISTReports = System.IO.File.Exists(reportPath) ? JsonConvert.DeserializeObject<List<BISTReport>>(System.IO.File.ReadAllText(reportPath)) : new List<BISTReport>();
            a = service.CalculateBISTProfit();
            UsdPrice = service.GetUsdTryPrice();
            var list = a.Values.First();
            satilan = list.Where(br => br.isPartiallySelled || br.isTotallySelled).OrderByDescending(br => br.BirimDegisimYuzde).ToList();
            elde = list.Where(br => !(br.isPartiallySelled || br.isTotallySelled)).OrderByDescending(br => br.BirimDegisimYuzde).ToList();
            BISTResults = elde.Union(satilan).ToList();

            double totalTutar = a.Keys.First().Keys.First();
            double currentTotal = a.Keys.First().Values.First();

            ViewData["TotalTutar"] = totalTutar;
            ViewData["TotalTotalKZ"] = currentTotal - totalTutar;
            ViewData["UsdPrice"] = UsdPrice;
            ViewData["TotalTutarUsd"] = service.TotalMaliyetUSD;
            ViewData["SimdikiToplam"] = currentTotal / UsdPrice;

            return RedirectToPage("Index");
        }

        public List<BISTResult> BISTResults { get; set; }
        public List<BISTReport> BISTReports { get; set; }
        public List<BISTResult> satilan { get; set; }
        public List<BISTResult> elde { get; set; }
        public Dictionary<Dictionary<double, double>, List<BISTResult>> a { get; set; }
        public double UsdPrice { get; private set; }
        public void OnGet()
        {
            double totalTutar = a.Keys.First().Keys.First();
            double currentTotal = a.Keys.First().Values.First();

            ViewData["TotalTutar"] = totalTutar;
            ViewData["TotalTotalKZ"] = currentTotal - totalTutar;
            ViewData["UsdPrice"] = UsdPrice;
            ViewData["TotalTutarUsd"] = service.TotalMaliyetUSD;
            ViewData["SimdikiToplam"] = currentTotal/UsdPrice;
        }
    }
}

BISTTool/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BISTTool.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BISTTool/Pages/Index.cshtml
@page
@model BISTTool.Pages.IndexModel

<div>USD/TRY: @ViewData["UsdPrice"]</div>
<p></p>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Lot</th>
            <th>Birim Maliyet</th>
            <th>Birim Fiyat</th>
            <th>Birim KZ</th>
            <th>Günlük Değişim</th>
            <th>Birim Değişim Yüzdesi</th>
            <th>Satılan Birim Satış Fiyatı</th>
            <th>Tutar</th>
            <th>Total KZ</th>
            <th>Toplam</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BISTResults)
        {
            @if (item.Name == "TRY") continue;

            @if (item.isTotallySelled)
            {
                <tr>
                    <td style="background-color:coral">@item.Name.Split('.')[0].ToUpperInvariant()</td>
                    <td>@(item.Miktar                         )</td>
                    <td>@(item.BirimMaliyet.ToString("N2") + " ₺"            )</td>
                    <td>@(item.BirimFiyat + " ₺"              )</td>
                     <td class="@(item.BirimKZ < 0 ? "red-background" : "green-background")">
                        @item.BirimKZ.ToString("N2") ₺
                    </td>
                    <td>@(item.GunlukDegisim.ToString("N2") + " %"           )</td>
                    <td>@(item.BirimDegisimYuzde.ToString("N2") + " %"       )</td>
                    <td>@(item.SatilanBirimSatisFiyati.ToString("N2") + " ₺" )</td>
                    <td>@(item.Tutar.ToString("N2")  + " ₺"                   )</td>
                    <td>@(item.TotalKZ.ToString("N2") + " ₺"                  )</td>
                    <td>@((item.TotalKZ + item.Tutar).ToString("N2") + " ₺"  )</td>
                </tr>
            }
            else
            {
                <tr>
                    <td style="background-color:aquamarine">@item.Name.Split('.')[0].ToUpperInvariant()</td>
                    <td>@(item.Miktar                         )</td>
                    <td>@(item.BirimMaliyet.ToString("N2") + " ₺"            )</td>
                    <td>@(item.BirimFiyat + " ₺"              )</td>
                    <td class="@(item.BirimKZ < 0 ? "red-background" : "green-background")">
                        @item.BirimKZ.ToString("N2") ₺
                    </td>
                    <td>@(item.GunlukDegisim.ToString("N2") + " %"           )</td>
                    <td>@(item.BirimDegisimYuzde.ToString("N2") + " %"       )</td>
                    <td>@("")</td>
                    <td>@(item.Tutar.ToString("N2") + " ₺"                   )
                    <td>@(item.TotalKZ.ToString("N2") + " ₺"                  )</td>
                    <td>@((item.TotalKZ + item.Tutar).ToString("N2") + " ₺"  )</td>
                </tr>
            }
        }
        <tr>
            <td>Toplam TL</td>
            <td colspan="7"></td>
            <td>@(((double)ViewData["TotalTutar"]).ToString("N2") + " ₺")</td>
            <td>@(((double)ViewData["TotalTotalKZ"]).ToString("N2") + " ₺")</td>
            <td>@(((double)ViewData["TotalTotalKZ"] + (double)ViewData["TotalTutar"]).ToString("N2") + " ₺")</td>
        </tr>
        <tr>
            <td>Toplam USD</td>
            <td colspan="7"></td>
            <td>@(((double)ViewData["TotalTutarUsd"]).ToString("N2") + " $")</td>
            <td>@(((double)ViewData["SimdikiToplam"] - (double)ViewData["TotalTutarUsd"]).ToString("N2") + " $")</td>
            <td>@(((double)ViewData["SimdikiToplam"]).ToString("N2") + " $")</td>
        </tr>
    </tbody>
</table>


<form method="post">
    <button type="submit" asp-page-handler="MyButtonClick">Yenile</button>
</form>

<p></p>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>Tarih</th>
            <th>USD/TRY</th>
            <th>Toplam Maliyet</th>
            <th>Toplam Maliyet USD</th>
            <th>Toplam Kar/Zarar</th>
            <th>Toplam Kar/Zarar USD</th>
            <th>Toplam Portföy</th>
            <th>Toplam Portföy USD</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BISTReports)
        {
            <tr>
                <td style="background-color:beige">@item.Date.ToLongDateString()</td>
                <td>@(item.USDTRY + " ₺")</td>
                <td>@(item.TotalMaliyet.ToString("N2") + " ₺"            )</td>
                <td>@(item.TotalMaliyetUSD.ToString("N2") + " $")</td>
                <td class="@(item.TotalKz < 0 ? "red-background" : "green-background")">
                    @item.TotalKz.ToString("N2") ₺
                </td>
                <td class="@(item.TotalKzUSD < 0 ? "red-background" : "green-background")">
                    @item.TotalKzUSD.ToString("N2") $
                </td>
                <td>@(item.PortfolioTotal.ToString("N2") + " ₺"           )</td>
                <td>@(item.PortfolioTotalUSD.ToString("N2") + " $"       )</td>
            </tr>
        }

    </tbody>
</table>




<script>
    // Function to refresh the page
    function refreshPage() {
        location.reload(); // Reload the page to rerun the OnGet method
    }

    // Attach an onclick event handler to the button
    document.getElementById("refreshButton").onclick = function () {
        refreshPage(); // Call the refreshPage function when the button is clicked
    };

    // Schedule the next refresh after 10 minutes
    setTimeout(refreshPage, 600000); // 600000 ms = 10 minutes
</script>

BISTTool/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BISTTool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BISTTool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BISTTool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BISTTool - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>